package drl;
import java.util.Map;
import static main.func.DaySinceLastEvent.run;

rule "함수 object 테스트 2"
	no-loop true
	lock-on-active true
	salience 1
	when
		$map : Map(
		eval(run($map.get("MPHON_COMB_YN"), $map.get("CUST_AGE")) == true)	)
	then
		$map.put("ruleId_560", 560);
		$map.put("campId_560", null);
		$map.put("salience_560", 1);
		$map.put("ruleNm_560", "함수 object 테스트 2");
		$map.put("targetType_560", "CUST");
end
